---
title             : "Introduction"
shorttitle        : "Moral Dilution"
author:
  - name          : "Cillian McHugh"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "University of Limerick, Limerick, Ireland, V94 T9PX"
    email         : "cillian.mchugh@ul.ie"
  - name          : "Marek McGann"
    affiliation   : "2"
  - name          : "Eric R. Igou"
    affiliation   : "1"
  - name          : "Elaine L Kinsella"
    affiliation   : "1"
affiliation:
  - id            : "1"
    institution   : "University of Limerick"
  - id            : "2"
    institution   : "Mary Immaculate College ~ University of Limerick"
author_note: >
  All procedures performed in studies involving human participants were approved by institutional research ethics committee and conducted in accordance with the Code of Professional Ethics of the Psychological Society of Ireland, and with the 1964 Helsinki declaration and its later amendments or comparable ethical standards. Informed consent was obtained from all individual participants included in the study. The authors declare that there are no potential conflicts of interest with respect to the research, authorship, and/or publication of this article. All authors consented to the submission of this manuscript.
abstract: >
  Across five studies we investigated the moral dilution effect.
keywords          : "keywords"
wordcount         : "TBC"
bibliography: "../resources/bib/My Library.bib"
cls: "../resources/bib/apa7.cls"
figsintext        : yes
figurelist        : yes
tablelist         : yes
footnotelist      : no
lineno            : yes
toc               : yes
lang              : "en-US"
documentclass     : "apa7"
output:
  papaja::apa6_word
editor_options: 
  chunk_output_type: console
---


```{r Introsetup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
# knitr::opts_chunk$set(eval = TRUE, echo = TRUE)
#knitr::opts_chunk$set(include = FALSE)
```




```{r introload_libraries_cogload}
rm(list = ls())
library(citr)
#install.packages("sjstats")
library(plyr)
library(foreign)
library(car)
library(desnum)
library(ggplot2)
library(extrafont)
#devtools::install_github("crsh/papaja")
library(papaja)
#library("dplyr")
library("afex")
library("tibble")
library(scales)
#install.packages("metap")
library(metap)
library(pwr)
library(lsr)
#install.packages("sjstats")
library(sjstats)
library(DescTools)
#inatall.packages("ggstatsplot")
#library(ggstatsplot)
library(VGAM)
library(nnet)
library(mlogit)
library(reshape2)
#install.packages("powerMediation")
library("powerMediation")


#source("load_all_data.R")

#devtools::install_github("benmarwick/wordcountaddin")
#library(wordcountaddin)
#wordcountaddin::text_stats("cogload_1to5_25Sept19.Rmd")


#library("papaja")
#library("wordcountaddin")
#wordcountaddin::word_count("Introduction.Rmd")
#devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
```


Recent developments in the psychology of moral judgments propose that making a moral judgment is an act of categorization [@mchugh_moral_2022]. A corollary of this view is that moral judgments vary depending on how well a target maps onto a template of a prototypical morally relevant act/actor [@schein_theory_2018]














